const EventData = {
  "011": {
    Eventname: "Robo War",
    Eventmentor: "Gaurav shukla",
    Eventmentoremail: "grvshukla24@gmail.com",
    Grouped: true,
    img: "runBhumi.jpg",
    EventClub: "ROBOTRAX CLUB",
    EventCode: "011",
  },
  "012": {
    Eventname: "Robo Race",
    Eventmentor: "Gaurav shukla",
    Eventmentoremail: "grvshukla24@gmail.com",
    Grouped: true,
    img: "roboRace.jpg",
    EventClub: "ROBOTRAX CLUB",
    EventCode: "012",
  },
  "013": {
    Eventname: "Line Follower Robot",
    Eventmentor: "Gaurav shukla",
    Eventmentoremail: "grvshukla24@gmail.com",
    Grouped: true,
    img: "LineFollowerRobot.jpg",

    EventClub: "ROBOTRAX CLUB",
    EventCode: "013",
  },
  "014": {
    Eventname: "Robo Soccer",
    Eventmentor: "Gaurav shukla",
    Eventmentoremail: "grvshukla24@gmail.com",
    Grouped: true,
    img: "RobotSoccer.jfif",

    EventClub: "ROBOTRAX CLUB",
    EventCode: "014",
  },
  "015": {
    Eventname: "Maze Solver",
    Eventmentor: "Gaurav shukla",
    Eventmentoremail: "grvshukla24@gmail.com",
    Grouped: true,
    img: "MazeSolver.jpg",

    EventClub: "ROBOTRAX CLUB",
    EventCode: "015",
  },
  "021": {
    Eventname: "Drone Race",
    Eventmentor: "Shubham singh",
    Eventmentoremail: "shubham2230singh@gmail.com",
    Grouped: true,
    img: "DroneRace.jfif",

    EventClub: "SYNERGY CLUB",
    EventCode: "021",
  },
  "022": {
    Eventname: "Aqua Race",
    Eventmentor: "Shubham singh",
    Eventmentoremail: "shubham2230singh@gmail.com",
    Grouped: true,
    img: "AquaRace.jpg",

    EventClub: "SYNERGY CLUB",
    EventCode: "022",
  },
  "023": {
    Eventname: "Robo Rumble",
    Eventmentor: "Shubham singh",
    Eventmentoremail: "shubham2230singh@gmail.com",
    Grouped: true,
    img: "RoboRumble.jpg",

    EventClub: "SYNERGY CLUB",
    EventCode: "023",
  },
  "024": {
    Eventname: "Drag & Place",
    Eventmentor: "Shubham singh",
    Eventmentoremail: "shubham2230singh@gmail.com",
    Grouped: true,
    img: "Drag&Place.jpg",

    EventClub: "SYNERGY CLUB",
    EventCode: "024",
  },
  "025": {
    Eventname: "Junk-War",
    Eventmentor: "Shubham singh",
    Eventmentoremail: "shubham2230singh@gmail.com",
    Grouped: false,
    img: "JunkWar.jpg",

    EventClub: "SYNERGY CLUB",
    EventCode: "025",
  },
  "031": {
    Eventname: "Chain reaction",
    Eventmentor: "Anshul Johari",
    Eventmentoremail: "johari.anshul8@gmail.com",
    Grouped: true,
    img: "ChainReaction.jpg",

    EventClub: "AERONAUTICS CLUB",
    EventCode: "031",
  },
  "032": {
    Eventname: "The Micrones",
    Eventmentor: "Anshul Johari",
    Eventmentoremail: "johari.anshul8@gmail.com",
    img: "TheMicrones.jfif",

    Grouped: false,
    EventClub: "AERONAUTICS CLUB",
    EventCode: "032",
  },
  "033": {
    Eventname: "Glider Plane",
    Eventmentor: "Anshul Johari",
    Eventmentoremail: "johari.anshul8@gmail.com",
    Grouped: true,
    img: "gliderPlaneDesign.jfif",

    EventClub: "AERONAUTICS CLUB",
    EventCode: "033",
  },
  "034": {
    Eventname: "CAD Tricks",
    Eventmentor: "Anshul Johari",
    Eventmentoremail: "johari.anshul8@gmail.com",
    img: "CadTricks.jpg",

    Grouped: false,
    EventClub: "AERONAUTICS CLUB",
    EventCode: "034",
  },
  "041": {
    Eventname: "Web Battle",
    Eventmentor: "Tej singh",
    Eventmentoremail: "tejsinghvns2002@gmail.com",
    img: "webbattle.jpeg",

    Grouped: false,
    EventClub: "EQUINOX & ILLUMINATI CLUB",
    EventCode: "041",
  },
  "042": {
    Eventname: "Beat-The-Bug",
    Eventmentor: "Tej singh",
    Eventmentoremail: "tejsinghvns2002@gmail.com",
    Grouped: false,
    img: "beatTheBug.jpg",
    EventClub: "EQUINOX & ILLUMINATI CLUB",
    EventCode: "042",
  },
  "043": {
    Eventname: "Db Knight",
    Eventmentor: "Tej singh",
    Eventmentoremail: "tejsinghvns2002@gmail.com",
    img: "DBKnight.jpg",
    Grouped: false,
    EventClub: "EQUINOX & ILLUMINATI CLUB",
    EventCode: "043",
  },
  "044": {
    Eventname: "C-Experts",
    Eventmentor: "Tej singh",
    Eventmentoremail: "tejsinghvns2002@gmail.com",
    Grouped: false,
    img: "Cexperts.jpg",
    EventClub: "EQUINOX & ILLUMINATI CLUB",
    EventCode: "044",
  },
  "045": {
    Eventname: "Tech-Play",
    Eventmentor: "Tej singh",
    Eventmentoremail: "tejsinghvns2002@gmail.com",
    img: "Techplay.jpg",
    Grouped: true,

    EventClub: "EQUINOX & ILLUMINATI CLUB",
    EventCode: "045",
  },
  "051": {
    Eventname: "Arz kiya hai",
    Eventmentor: "Suryansh shrivastav",
    Eventmentoremail: "devanshsri2017@gmail.com",
    img: "ArzKiyaHai.jpg",
    Grouped: false,
    EventClub: "LITERARAY CLUB",
    EventCode: "051",
  },
  "052": {
    Eventname: "Let's Get Quizzical",
    Eventmentor: "Suryansh shrivastav",
    Eventmentoremail: "devanshsri2017@gmail.com",
    Grouped: true,
    img: "LetsGetQuizzical.jpg",

    EventClub: "LITERARAY CLUB",
    EventCode: "052",
  },
  "053": {
    Eventname: "Spell-O-Ween",
    Eventmentor: "Suryansh shrivastav",
    Eventmentoremail: "devanshsri2017@gmail.com",
    img: "SpellOWeen.jfif",
    Grouped: false,
    EventClub: "LITERARAY CLUB",
    EventCode: "053",
  },
  "054": {
    Eventname: "Escape The Room",
    Eventmentor: "Suryansh shrivastav",
    Eventmentoremail: "devanshsri2017@gmail.com",
    img: "EscapeTheRoom.jfif",
    Grouped: true,

    EventClub: "LITERARAY CLUB",
    EventCode: "054",
  },
  "055": {
    Eventname: "Word Bee",
    img: "WordBee.jpg",
    Eventmentor: "Suryansh shrivastav",
    Eventmentoremail: "devanshsri2017@gmail.com",
    Grouped: false,
    EventClub: "LITERARAY CLUB",
    EventCode: "055",
  },
  "061": {
    Eventname: "Polaroid Exposure",
    Eventmentor: "Shubhi Saxena",
    Eventmentoremail: "shubhisaxena829@gmail.com",
    img: "polaroidExposure.jpg",
    Grouped: false,
    EventClub: "MRC CLUB",
    EventCode: "061",
  },

  "062": {
    Eventname: "Pictograph/Logograph Designing",
    img: "Pictograoh.jfif",
    Eventmentor: "Shubhi Saxena",
    Eventmentoremail: "shubhisaxena829@gmail.com",
    Grouped: false,
    EventClub: "MRC CLUB",
    EventCode: "062",
  },
  "071": {
    Eventname: "Pharma desk",
    img: "PharmaDesk.jpg",
    Eventmentor: "Shruti saxena",
    Eventmentoremail: "saxenashruti422@gmail.com",
    Grouped: true,

    EventClub: "PHARMQUIMICA CLUB",
    EventCode: "071",
  },
  "072": {
    Eventname: "Collage-O-Fact",
    img: "collage-o-fact.jpg",
    Eventmentor: "Shruti saxena",
    Eventmentoremail: "saxenashruti422@gmail.com",
    Grouped: true,

    EventClub: "PHARMQUIMICA CLUB",
    EventCode: "072",
  },
  "073": {
    Eventname: "Pioneerdom",
    img: "Pioneerdom.jpg",
    Eventmentor: "Shruti saxena",
    Eventmentoremail: "saxenashruti422@gmail.com",
    Grouped: true,

    EventClub: "PHARMQUIMICA CLUB",
    EventCode: "073",
  },
  "074": {
    Eventname: "Pharmesquisser",
    img: "Pharmasequisser.jpg",
    Eventmentor: "Shruti saxena",
    Eventmentoremail: "saxenashruti422@gmail.com",
    Grouped: false,
    EventClub: "PHARMQUIMICA CLUB",
    EventCode: "074",
  },
  "081": {
    Eventname: "Technical Painting",
    Eventmentor: "Vaishnavi Sharma",
    img: "TechnicalPainting.jpg",
    Eventmentoremail: "vaishnavhisharma9909@gmai.com",
    Grouped: false,
    EventClub: "DESIGN CLUB",
    EventCode: "081",
  },
  "082": {
    Eventname: "Multimedia Art",
    Eventmentor: "Vaishnavi Sharma",
    img: "MultimediaArt.jpg",
    Eventmentoremail: "vaishnavhisharma9909@gmai.com",
    Grouped: false,
    EventClub: "DESIGN CLUB",
    EventCode: "082",
  },
  "083": {
    Eventname: "Best Out of Waste",
    Eventmentor: "Vaishnavi Sharma",
    Eventmentoremail: "vaishnavhisharma9909@gmai.com",
    img: "BestOutOfWaste.jpg",
    Grouped: false,
    EventClub: "DESIGN CLUB",
    EventCode: "083",
  },
  "084": {
    Eventname: "Quill The Techvyom",
    Eventmentor: "Vaishnavi Sharma",
    Eventmentoremail: "vaishnavhisharma9909@gmai.com",
    img: "QuillTheTechvyom.jpg",
    Grouped: false,
    EventClub: "DESIGN CLUB",
    EventCode: "084",
  },
  "091": {
    Eventname: "BGMI",
    Eventmentor: "TYRO",
    Eventmentoremail: "techvyomsrms@gmail.com",
    img: "bgmi.jpg",
    Grouped: false,
    EventClub: "LAN WAR",
    EventCode: "091",
  },
  "092": {
    Eventname: "FIFA",
    Eventmentor: "TYRO",
    img: "fifa.jpg",
    Eventmentoremail: "techvyomsrms@gmail.com",
    Grouped: false,
    EventClub: "LAN WAR",
    EventCode: "092",
  },
  "093": {
    Eventname: "Mini-Militia",
    Eventmentor: "TYRO",
    Eventmentoremail: "techvyomsrms@gmail.com",
    img: "MiniMilitia.jpg",
    Grouped: true,
    EventClub: "LAN WAR",
    EventCode: "093",
  },
  101: {
    Eventname: "Tech Gallery-Medical",
    Eventmentor: "TYRO",
    img: "techGallery(medical).jpg",
    Eventmentoremail: "techvyomsrms@gmail.com",
    Grouped: false,
    EventClub: "OPEN EVENTS",
    EventCode: "101",
  },
  102: {
    Eventname: "Tech Gallery-Technical engineering",
    Eventmentor: "TYRO",
    Eventmentoremail: "techvyomsrms@gmail.com",
    Grouped: false,
    img: "TechGallery(technicalEngineering).jpg",
    EventClub: "OPEN EVENTS",
    EventCode: "102",
  },
  103: {
    Eventname: "Tech Quiz",
    Eventmentor: "Tej singh",
    Eventmentoremail: "tejsinghvns2002@gmail.com",
    img: "TechQuiz.jpg",
    Grouped: false,
    EventClub: "OPEN EVENTS",
    EventCode: "103",
  },
  104: {
    Eventname: "PLC Designing",
    Eventmentor: "Shubham",
    Eventmentoremail: "shubham2230singh@gmail.com",
    img: "PLCDesigning.jpg",
    Grouped: false,
    EventClub: "OPEN EVENTS",
    EventCode: "104",
  },
  105: {
    Eventname: "3D-Printing",
    Eventmentor: "Gaurav shukla",
    img: "3DPrinting.jpg",
    Eventmentoremail: "grvshukla24@gmail.com",
    Grouped: false,
    EventClub: "OPEN EVENTS",
    EventCode: "105",
  },
};
module.exports = EventData;
